server.name: kibana
server.host: "0.0.0.0"
server.port: 5601

# Elasticsearch connection
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "changeme123"

# Monitoring
monitoring.ui.container.elasticsearch.enabled: true

# Security
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d"

# Reporting  
xpack.reporting.enabled: true
xpack.reporting.kibanaServer.hostname: localhost

# Localization
i18n.locale: "en"

# Logging
logging.root.level: info